### PR TITLE
update method scraper to find <a> links within <table>

### PR DESCRIPTION
**Pull request by alexagranov**
The method scraper was looking for `<a>` tags within a class of `.card` but Slack has revamped their Methods page to remove that class.  As a result, we've missed out on a few tasty API additions, like `chat.postEphemeral` and others.

Now just looking for `<a>` tags within `<table>`.

### CODE REVIEW

**Comment by dblock** [comment]
Thanks for this!

**Comment by dblock** [comment]
@alexagranov Do you want to join the collaborators group? Could use some occasional help, just trying to expand the maintainers of this.

**Comment by alexagranov** [comment]
@dblock sure thing!  I'm already one for slack-ruby-bot-server...

**Comment by dblock** [comment]
Added. Welcome.

**Pull request merged**
