### PR TITLE
Migrate Travis to GitHub Actions

### LINKED ISSUE #28: Document how to do an update without cron or how to kick off cron
We had a fix in https://github.com/slack-ruby/slack-api-ref/pull/27, but then waited 24 hours for cron on Travis to do https://github.com/slack-ruby/slack-api-ref/commit/f257c8b1eb802b2aa3c335947eee7bc2433967a4. Doing this manually would have required gymnastics, ie. setting `GH_TOKEN` and running `scripts/updade`.

### LINKED ISSUE #45: Migrate to GitHub Actions
Also it seems like slack-api-ref hasn't seen any updates for a while, Travis-CI was migrated from .org to .com, but I think we should replace that with GHA because that's just nonsense.

### PR DESCRIPTION
**Pull request by duffn**
This migrates Travis CI to GitHub Actions.

- Moved the update shell script to actions steps
- Example commit on testing branch: https://github.com/slack-ruby/slack-api-ref/commit/0dd1ef62e731e72e219e72280a31b66d231bdfff
- Chose cron time based upon past commits in the repo

Closes #45.
Closes #28.

### CODE REVIEW

**Comment by dblock** [comment]
Amazing. Update https://github.com/slack-ruby/slack-api-ref/blob/master/CRON.md as well?

**Comment by duffn** [comment]
Ah, yup missed that. Updated.

**Review by dblock — APPROVED** [review]
I believe you can also configure the workflow in a way that allows it to be manually triggered. This way we can force cron on demand.

**Comment by duffn** [comment]
Confirmed a successful scheduled run here https://github.com/slack-ruby/slack-api-ref/commit/9a0270a581e994c141e3a7363186300936ee3193

**Pull request merged**
