### PR TITLE
Adjust update script to push to master

### PR DESCRIPTION
**Pull request by mre**
Currently travis is not pushing to master. Trying to fix that with this PR.
That's a follow up to #14. 

Main changes:
* Update git rev to push to master
* Adjust commit message

### CODE REVIEW

**Comment by mre** [comment]
Oh hey! It was updating the API. Seems like it also included the vendor folder in the build, though. Still: main mission accomplished, so let's call it a success. 😅

**Comment by dblock** [comment]
It was a typo in `.gitignore` file name :)

I `git reset --hard HEAD~1` amended the file name in the title and force pushed, so we don't get the vendor folder in git history. 

Want to rerun the cron?

**Comment by mre** [comment]
Yeah, just noticed. Sorry for the fuss. I actually did the same but we should be fine now.
Triggering a rebuild.

**Comment by mre** [comment]
Much better now. I guess we're good. 🎉

**Comment by dblock** [comment]
Nice work, I'll close #14

**Pull request merged**
