### PR TITLE
Add automatic update functionality

### PR DESCRIPTION
**Pull request by mre**
So this is my attempt to introduce an automatic update functionality to the project (#12).
On my fork the build was successful but I couldn't see any commit from the bot yet.

[Here's an example build](https://travis-ci.org/mre/slack-api-ref/builds/208018831)
Note that it's adding a bunch of vendor files to git. I assume this is because there was no `.gitignore` file on the master branch when it was pushing.

I suggest the following:
1. Please have a quick look at the code.
2. Let's merge it as soon as the PR looks good.
3. We'll trigger a cron build on master and... profit?

### CODE REVIEW

**Comment by dblock** [comment]
This is great. Can we cleanup .gitignore to only have things that we care about? Like `vendor`? Everything else is superfluous.

**Comment by mre** [comment]
Yup. Removed the entries I deemed unnecessary. 👍

**Comment by dblock** [comment]
Merged, lets see if this worked?

**Comment by mre** [comment]
Cool. Will set up the cronjob now. One sec.

**Comment by mre** [comment]
Added cronjob. Starting in one minute. Fingers crossed.

**Comment by mre** [comment]
Forgot the GH_TOKEN. Let's try again. 😊

**Comment by mre** [comment]
Sooo... it built successfully but it pushed exactly... nothing to master. 😁 
I have the suspicion that it's because of that: http://stackoverflow.com/a/36941221
Will create another PR for the change.

**Pull request merged**
