### PR TITLE
fix localizing arguments section on method page

### PR DESCRIPTION
**Pull request by manuelmeurer**
Refs https://github.com/slack-ruby/slack-ruby-client/issues/193

### CODE REVIEW

**Comment by dblock** [comment]
Thanks! @manuelmeurer want in on this project and help us out with future maintenance?

**Comment by dblock** [comment]
We need to either wait for cron to run or figure out a way to trigger it or modify the script not to care about GH_TOKEN next to get this stuff working again.

**Comment by manuelmeurer** [comment]
Yeah sure, would love to help out! :)

**Comment by manuelmeurer** [comment]
Cron will run within the next 24 hours, right? If so, let's just wait for that.

**Comment by dblock** [comment]
Worked.

**Pull request merged**
